server {
    listen 80;
    server_name _;
    
    # Raíz donde se alojará la build compilada de Astro
    root /usr/share/nginx/html;
    index index.html;

    # Compresión GZIP: Crucial para reducir peso de HTML/CSS/JS al enviarlo a la red
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6; # Nivel de compresión óptimo entre peso y CPU
    gzip_types text/plain text/css text/xml application/json application/javascript application/rss+xml application/atom+xml image/svg+xml;
    gzip_min_length 256;

    # Headers de Seguridad básicos
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    # Bloque Principal: Fallback SPA para Astro
    location / {
        # Si el archivo pedido no existe físicamente (.html, .css, etc), probar ruta, o devolver 404
        try_files $uri $uri/ /index.html;
    }

    # Políticas Cache Ultraligeras (Cache-Control al Máximo para Archivos Estáticos)
    # Astro renombra estáticos en _astro/ con hash, por lo cual es seguro cachearlos 1 año (max-age).
    location ~* \.(?:css|js|woff2?|eot|ttf|otf|svg|png|jpg|jpeg|gif|webp|ico)$ {
        expires 1y;
        access_log off;
        add_header Cache-Control "public, max-age=31536000, immutable";
        try_files $uri =404;
    }

    # Caché a muy corto nivel (O no cache) para el HTML base
    location ~* \.(html)$ {
        expires -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    }
}
